name: Bug report
description: File a bug report
labels: [bug]
body:
  - type: textarea
    id: describe
    attributes:
      label: Describe the bug
      description: What happened and what did you expect?
      placeholder: Clear, concise description
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      placeholder: 1) ...
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version / commit
